@startuml

class Subject {
    observers
    attach(Observer)
    detach(Observer)
    notify()
}

class Observer {
    update()
}

class View{


Tastatur abfragen()
Menu()
Spiefeld darstellen()

}

class Controller{

}

class Schlange{
Anzahl Körperteil
Crash
}

class Futter{
Typ
}

class Bonusfutter{
}

class Spielfeld{
rahmen
new game()
pause()
punktestand
game over anzeige
position
speed
rangliste
}

Spielfeld -- Schlange
Spielfeld -- Futter
Futter <|-- Bonusfutter
Subject <|-- Spielfeld
Subject --> Observer
Subject <|-- View
Controller --|> Observer
Controller --|> View
Controller --|> Spielfeld
@enduml
