@startuml

class Schlange{
Anzahl Körperteil
}

class Futter{
Typ
}

class Bonusfutter{
}

class Spielfeld{
rahmen
new game()
pause()
punktestand
game over anzeige
position
} 

class Bewegungen{
Tastatur abfragen()
} 

class Crashing{
Rand
} 

class Menu{
speed
rangliste
} 

Spielfeld -- Schlange
Spielfeld -- Futter
Spielfeld -- Bewegungen
Spielfeld -- Crashing
Spielfeld -- Menu
Futter <|-- Bonusfutter
@enduml
