@startuml

class Subject {
    observers
    attach(Observer)
    detach(Observer)
    notify()
}

class Observer {
    update()
}

class View #yellow{
keyboard_handler()
draw_background()
draw_buttons()
draw_snake()
draw_food()
}

class Controller #lightgreen{

}

class Snake #lightblue{
Anzahl Körperteil
Crash
move_snake()
grow_snake()
check_self_crash()
}

class Field #lightblue{
new game()
pause()
punktestand
game over anzeige
snake position
food position
speed
food()
}

Field --> Snake
Subject <|-- Field
Subject --> Observer
Subject <|-- View
Controller --|> Observer
Controller --> View
Controller --> Field
@enduml
